// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW5jPUqqbo_xEFwOsWh8_c3ruA7anSQrU',
    appId: '1:973563412868:web:ace980e01142721b26ddd1',
    messagingSenderId: '973563412868',
    projectId: 'my-homework-ab6a7',
    authDomain: 'my-homework-ab6a7.firebaseapp.com',
    storageBucket: 'my-homework-ab6a7.firebasestorage.app',
    measurementId: 'G-CTLWKQZP12',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWuEiO0RT3bUgFDDPYzbQrTTmkP8VkeHA',
    appId: '1:973563412868:android:b4818bb60f7e3e6f26ddd1',
    messagingSenderId: '973563412868',
    projectId: 'my-homework-ab6a7',
    storageBucket: 'my-homework-ab6a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC4AKjQUbDY7XYxHJiYUVN6tCc_1pIJU4',
    appId: '1:973563412868:ios:1f42031040c3ca2c26ddd1',
    messagingSenderId: '973563412868',
    projectId: 'my-homework-ab6a7',
    storageBucket: 'my-homework-ab6a7.firebasestorage.app',
    iosBundleId: 'com.example.tasksApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCC4AKjQUbDY7XYxHJiYUVN6tCc_1pIJU4',
    appId: '1:973563412868:ios:1f42031040c3ca2c26ddd1',
    messagingSenderId: '973563412868',
    projectId: 'my-homework-ab6a7',
    storageBucket: 'my-homework-ab6a7.firebasestorage.app',
    iosBundleId: 'com.example.tasksApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAW5jPUqqbo_xEFwOsWh8_c3ruA7anSQrU',
    appId: '1:973563412868:web:bd7d33e65263f1c026ddd1',
    messagingSenderId: '973563412868',
    projectId: 'my-homework-ab6a7',
    authDomain: 'my-homework-ab6a7.firebaseapp.com',
    storageBucket: 'my-homework-ab6a7.firebasestorage.app',
    measurementId: 'G-E6HJHRDKQE',
  );
}
